### ISSUE TITLE
I think the benchmark is faulty because the payload is too large

### ISSUE THREAD

**Issue by EdwardDrapkin** [arendjr/fetch-vs-xhr-perf#1]
I think this benchmark is misleading and faulty and is benchmarking JSON parsing rather than the HTTP APIs themselves.

If you change the test-data payload to simply `[{ "_id": "123456" }]`, you get wildly different results:

```
useFetch x 414 ops/sec ±1.36% (53 runs sampled)
useXhr x 418 ops/sec ±2.00% (55 runs sampled)
useXhrWithResponseTypeJson x 415 ops/sec ±1.62% (54 runs sampled)
```

versus:

```
useFetch x 9.69 ops/sec ±2.33% (48 runs sampled)
useXhr x 13.82 ops/sec ±1.50% (34 runs sampled)
useXhrWithResponseTypeJson x 11.81 ops/sec ±1.56% (30 runs sampled)
```

It seems that the slowdown seems to come from parsing 9MB of JSON, rather than from the HTTP APIs themselves.  And since I would wager most JSON payloads parsed are well under 10kB, let alone 10MB, it seems like the results with the smaller payload are more indicative of what engineers will see in their code.

**Comment by arendjr** [comment]
What's misleading about that? I explain it in the first paragraph:

> This benchmark compares three different approaches to fetching and parsing a large JSON file

It's the point of the benchmark to test how the different approaches deal with large JSON payloads.
